// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzrgdpYoX1RKdExyv2Kp-GK9M-43WZT0',
    appId: '1:341505346908:ios:906455867e6998e8a5c599',
    messagingSenderId: '341505346908',
    projectId: 'dto-exercice-15bf2',
    storageBucket: 'dto-exercice-15bf2.firebasestorage.app',
    iosBundleId: 'be.hepl.dtoexercice.dtoExercice',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmJ6NBqpjElABBAvEo0WISye3z2EO9es8',
    appId: '1:341505346908:android:81ff7534b117ef72a5c599',
    messagingSenderId: '341505346908',
    projectId: 'dto-exercice-15bf2',
    storageBucket: 'dto-exercice-15bf2.firebasestorage.app',
  );

}